services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www/html:cached
      - laravel_project_storage:/var/www/html/storage
      - laravel_project_bootstrap_cache:/var/www/html/bootstrap/cache
      - laravel_project_vendor:/var/www/html/vendor
    networks:
      - laravel_project_network

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_project_network

  mysql:
    build:
      context: .
      dockerfile: .docker/mysql/Dockerfile
    container_name: laravel_mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=laravel_project
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - laravel_project_mysql:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel_project_network
      
volumes:
  laravel_project_storage:
  laravel_project_bootstrap_cache:
  laravel_project_vendor:
  laravel_project_mysql:
    driver: local

networks:
  laravel_project_network:
    driver: bridge